[package]
name = "tessellation"
version = "0.1.0"
authors = ["David Rasch"]
edition = "2018"

[features]

[dependencies]
minifb = { version="0.15.3" }
euclid = "0.20.7"
raqote = { version="0.7.11", default-features=false}
serde = { version="1.0.104" }
