[package]
name = "tessellations"
version = "0.1.1"
authors = ["David Rasch"]
license= "GPL-3.0"
edition = "2018"
repository = "https://github.com/dcrasch/tir"
keywords = ["tessellation", "graphics"]
description = "Library to create and draw periodic tilings of the plane."
docs = "https://docs.rs/tessellations/"
[lib]
name="tessellations"

[dependencies]
raqote = { version="0.8", default-features=false }
serde = { version="1.0.104", features = ["derive"] }
euclid = "0.20" ##must be same version as raqote

[dev-dependencies]
serde_json = "1.0.48"
