[package]
name = "tir-web"
version = "0.1.0"
authors = ["David Rasch"]
license= "GPL-3.0"
edition = "2018"
repository = "https://github.com/dcrasch/tir"
description = "Tessellation for the web"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.58"
serde_json = "1.0.48"
tessellations = { path = "../tessellations" }
raqote = { version="0.7.11", default-features=false}
euclid = "0.20.7"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'ImageData',

  'CssStyleDeclaration',
  'Document',
  'Element',
  'EventTarget',
  'HtmlCanvasElement',
  'HtmlElement',
  'MouseEvent',
  'Node',
  'Window'
]